[default]
binary = false
check-filename = true

[default.extend-identifiers]

[default.extend-words]

[files]
extend-exclude = [
  ".git/",
  "~/.asdf/installs/flutter",
  "~/.asdf/installs/dart",
]

[type.log]
check-file = false
